void limpa_buffer(void);
void print_dados(void);
void error(void);
int ehDigito(char c);
int ehDigitoMax(char c, char max);
int ehLetra(char c);
int ehBissexto(int aa);
int ehData(int dd, int mm, int aa);
int valNome(char* nome);
int valData(char* data);
int val_id(char* id, int tam);
