void limpa_buffer(void);
int conta_entrada1(char *entrada);
int conta_entrada2(char *entrada);
int ehDigito(char c);
int ehDigitoMax(char c, char max);
int ehLetra(char c);
int ehBissexto(int aa);
int ehData(int dd, int mm, int aa);
int valNome(char *nome);
int valData(char *data);
int val_id(char *id, int tam);
int val_email(char *email);
float ehdinheiro(char *c);
int validarFone(char *fone);
int validarCPF(char *cpf);
int ehHora(char c);
int val_hour(char *hour);
