void get_nome(char* nome, char* modulo);
void get_nome_upd(char *nome, char* modulo);
void get_cache(char* cache, char* modulo);
void get_cache_upd(char* cache, char* modulo);
void get_email(char* email, char* modulo);
void get_email_upd(char* email, char* modulo);
void get_num(char* num, char* modulo, int tam);
void get_num_upd(char* num, char* modulo);
void get_id(char* id, char* modulo, int tam);
void get_quant_cad(char* quant, char* modulo);
void get_quant_cad_upd(char* quant, char* modulo);
void get_quant_venda(char* quant, char* modulo);
void get_quant_venda_upd(char* quant, char* modulo);
void get_valor(char* valor, char* modulo);
void get_valor_upd(char* valor, char* modulo);
void get_cpf(char* cpf);
void get_cpf_upd(char* cpf);
void get_data(char* data);
void get_data_upd(char* data);
void get_hour(char* hour);
void get_hour_upd(char* data);
void screen_null_id_error(char* modulo);
void screen_error_input(void);
void screen_error_input_name(void);
void screen_error_input_resp(void);
void screen_error_input_id(char* chave);
void screen_error_input_n_exist(char* chave);
char certeza_upd(char* modulo);
char certeza_del(char* modulo);
