void limpa_buffer(void);
void limpa_linha(void);
int val_entrada(char *entrada);
int ehDigito(char c);
int ehDigitoMax(char c, char max);
int ehDigitoDinheiro(char c);
int ehdinheiro(char *c);
int ehLetra(char c);
int ehLetraeEspacoeAcento(char c);
int valNome(char *nome);
int ehBissexto(int aa);
int ehData(int dd, int mm, int aa);
int data_validacao(char data[]);
int data_validacao_busc(char data[]);
char* corrige_data(char *data);
int valData(char *data);
int valDataBusc(char *data);
int compara_datas(char *data, char *data_inicial, char *data_final);
int val_id(char *id);
int val_email(char *email);
int validarFone(char *fone);
int validarCPF(char *cpf);
int ehHora(char c);
int hour_validacao(char hour[]);
char* corrige_hour(char hour[]);
int val_hour(char hour[]);
char* input(void);
char* duplica(char* s);
char *leLinha(char *linha, int tamanhoMaximo);
char* centralizar_texto(char* texto, int tam, int horizontal);
